spring:
  application:
    name: spring-security-oauth2-content-resource
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 721000
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
server:
  port: 8081
  servlet:
    context-path: /content

mybatis:
  type-aliases-package: com.tang.oauth.content.resource.domain
  mapper-locations: classpath:mapper/*.xml

# 资源服务器  对接  认证服务器
security:
  oauth2:
    client:
      client-id: client     # 客户端 client_id
      client-secret: secret  # 客户端 securet
      access-token-uri: http://localhost:8080/oauth/token   #请求token地址
      user-authorization-uri: http://localhost:8080/oauth/authorize   #授权地址
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token   #验证token地址